FROM debian:stretch-slim
# mkdir the man/man1 directory due to Debian bug #863199
RUN set -exu;\
    export http_proxy=$HTTP_PROXY; \
    apt-get update; \
    mkdir -p /usr/share/man/man1; \
    apt-get install --yes --no-install-recommends \
      autoconf \
      automake \
      bubblewrap \
      bzip2 \
      cmake \
      curl \
      g++ \
      gcc \
      git-core \
      libc6-dev \
      libgmp-dev \
      libmpfr-dev \
      libsqlite3-dev \
      make \
      openjdk-8-jdk-headless \
      patch \
      pkg-config \
      python2.7 \
      sudo \
      unzip \
      xz-utils \
      zlib1g-dev \
    ; apt-get clean;rm -rf /var/lib/apt/lists/*

